# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# The default values used in the docker build commands are the root
# directory '.' and the dockerfile name of 'Dockerfile'. If there is 
# a need to change these do so in your local workflow template (this file) and
# change them there. HINT: Look at the bottom of this file.

# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and generates an
# SBOM via Anchore's Syft tool

# For more information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype

# For more information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft

name: ConsoleDot Platform Security Scan

on:
  push:
    branches: [ "main", "master", "security-compliance" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "master", "security-compliance" ]

jobs:
  PlatSec-Security-Workflow:
    uses: ./.github/workflows/platsec-security-scan-reusable-workflow.yml
    # Uncomment the 3 lines below if you are using something other than the
    # the defaults of root '.' for the path and 'Dockerfile' for the
    # Dockerfile name.
    # with:
    #  dockerfile_path: 'THE DIRECTORY THE DOCKERFILE IS IN' #example dockerfile_path: './test'
    #  dockerfile_name: 'THE NAME OF THE DOCKERFILE' #example dockerfile_name: 'dockerfile'
